# Generated by Django 2.1.5 on 2019-02-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='subject',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='hit',
        ),
    ]
