# Generated by Django 2.1.5 on 2019-02-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardd', '0003_auto_20190218_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
    ]
